name: Python package

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: book
    - name: Checkout site
      uses: actions/checkout@v2
      with:
        repository: maki-nage/maki-nage.github.io
        path: www
    - name: Install dependencies
      run: |
        python -m pip install sphinx sphinx-rtd-theme
    - name: Make doc
      run: |
        ls
        cd book && make html
    - name: Publish master
      run: |
        pwd
        ls
        cd www
        git config user.name github-actions
        git config user.email github-actions@github.com
        git rm -rf doc/makinage-book/latest
        cp -r ../book/_build/html/* www/doc/makinage-book/latest/
        git add doc/makinage-book/latest
        git commit -m "book: push latest"
        git push
